// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Tomboy.NoteStatistics {
    
    
    public partial class NoteStatsDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label noteTitle;
        
        private Gtk.Table table1;
        
        private Gtk.Label label14;
        
        private Gtk.Label label15;
        
        private Gtk.Label label16;
        
        private Gtk.Label label17;
        
        private Gtk.Label label2;
        
        private Gtk.Label noteCharsNoSpaces;
        
        private Gtk.Label noteCharsSpaces;
        
        private Gtk.Label noteLines;
        
        private Gtk.Label noteWords;
        
        private Gtk.Label selCharsNoSpaces;
        
        private Gtk.Label selCharsSpaces;
        
        private Gtk.Label selHeader;
        
        private Gtk.Label selLines;
        
        private Gtk.Label selWords;
        
        private Gtk.Button buttonCancel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Tomboy.NoteStatistics.NoteStatsDialog
            this.Name = "Tomboy.NoteStatistics.NoteStatsDialog";
            this.Title = Mono.Unix.Catalog.GetString("Note Statistics");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Tomboy.NoteStatistics.NoteStatsDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.noteTitle = new Gtk.Label();
            this.noteTitle.Name = "noteTitle";
            this.noteTitle.Xalign = 0F;
            this.noteTitle.LabelProp = Mono.Unix.Catalog.GetString("<b>Note Title</b>");
            this.noteTitle.UseMarkup = true;
            this.noteTitle.Wrap = true;
            this.vbox2.Add(this.noteTitle);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.noteTitle]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.Xalign = 0F;
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Lines");
            this.table1.Add(this.label14);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label14]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label15 = new Gtk.Label();
            this.label15.Name = "label15";
            this.label15.Xalign = 0F;
            this.label15.LabelProp = Mono.Unix.Catalog.GetString("Words");
            this.table1.Add(this.label15);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label15]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.Xalign = 0F;
            this.label16.LabelProp = Mono.Unix.Catalog.GetString("Characters (with spaces)");
            this.table1.Add(this.label16);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label16]));
            w5.TopAttach = ((uint)(3));
            w5.BottomAttach = ((uint)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label17 = new Gtk.Label();
            this.label17.Name = "label17";
            this.label17.Xalign = 0F;
            this.label17.LabelProp = Mono.Unix.Catalog.GetString("Characters (no spaces)");
            this.table1.Add(this.label17);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label17]));
            w6.TopAttach = ((uint)(4));
            w6.BottomAttach = ((uint)(5));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Note");
            this.label2.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.noteCharsNoSpaces = new Gtk.Label();
            this.noteCharsNoSpaces.Name = "noteCharsNoSpaces";
            this.noteCharsNoSpaces.Xalign = 1F;
            this.noteCharsNoSpaces.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.noteCharsNoSpaces.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.noteCharsNoSpaces);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.noteCharsNoSpaces]));
            w8.TopAttach = ((uint)(4));
            w8.BottomAttach = ((uint)(5));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.noteCharsSpaces = new Gtk.Label();
            this.noteCharsSpaces.Name = "noteCharsSpaces";
            this.noteCharsSpaces.Xalign = 1F;
            this.noteCharsSpaces.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.noteCharsSpaces.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.noteCharsSpaces);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.noteCharsSpaces]));
            w9.TopAttach = ((uint)(3));
            w9.BottomAttach = ((uint)(4));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.noteLines = new Gtk.Label();
            this.noteLines.Name = "noteLines";
            this.noteLines.Xalign = 1F;
            this.noteLines.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.noteLines.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.noteLines);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.noteLines]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.noteWords = new Gtk.Label();
            this.noteWords.Name = "noteWords";
            this.noteWords.Xalign = 1F;
            this.noteWords.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.noteWords.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.noteWords);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.noteWords]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selCharsNoSpaces = new Gtk.Label();
            this.selCharsNoSpaces.Name = "selCharsNoSpaces";
            this.selCharsNoSpaces.Xalign = 1F;
            this.selCharsNoSpaces.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.selCharsNoSpaces.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.selCharsNoSpaces);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.selCharsNoSpaces]));
            w12.TopAttach = ((uint)(4));
            w12.BottomAttach = ((uint)(5));
            w12.LeftAttach = ((uint)(2));
            w12.RightAttach = ((uint)(3));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selCharsSpaces = new Gtk.Label();
            this.selCharsSpaces.Name = "selCharsSpaces";
            this.selCharsSpaces.Xalign = 1F;
            this.selCharsSpaces.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.selCharsSpaces.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.selCharsSpaces);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.selCharsSpaces]));
            w13.TopAttach = ((uint)(3));
            w13.BottomAttach = ((uint)(4));
            w13.LeftAttach = ((uint)(2));
            w13.RightAttach = ((uint)(3));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selHeader = new Gtk.Label();
            this.selHeader.Name = "selHeader";
            this.selHeader.Xalign = 1F;
            this.selHeader.LabelProp = Mono.Unix.Catalog.GetString("Selection");
            this.selHeader.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.selHeader);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.selHeader]));
            w14.LeftAttach = ((uint)(2));
            w14.RightAttach = ((uint)(3));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selLines = new Gtk.Label();
            this.selLines.Name = "selLines";
            this.selLines.Xalign = 1F;
            this.selLines.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.selLines.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.selLines);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.selLines]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.LeftAttach = ((uint)(2));
            w15.RightAttach = ((uint)(3));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selWords = new Gtk.Label();
            this.selWords.Name = "selWords";
            this.selWords.Xalign = 1F;
            this.selWords.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.selWords.Justify = ((Gtk.Justification)(1));
            this.table1.Add(this.selWords);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.selWords]));
            w16.TopAttach = ((uint)(2));
            w16.BottomAttach = ((uint)(3));
            w16.LeftAttach = ((uint)(2));
            w16.RightAttach = ((uint)(3));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w18.Position = 0;
            w18.Expand = false;
            w18.Fill = false;
            // Internal child Tomboy.NoteStatistics.NoteStatsDialog.ActionArea
            Gtk.HButtonBox w19 = this.ActionArea;
            w19.Name = "dialog1_ActionArea";
            w19.Spacing = 6;
            w19.BorderWidth = ((uint)(5));
            w19.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-close";
            this.AddActionWidget(this.buttonCancel, -7);
            Gtk.ButtonBox.ButtonBoxChild w20 = ((Gtk.ButtonBox.ButtonBoxChild)(w19[this.buttonCancel]));
            w20.Expand = false;
            w20.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.Response += new Gtk.ResponseHandler(this.OnResponse);
        }
    }
}
